### ISSUE TITLE
Broken/Not Working?

### ISSUE THREAD

**Issue by LilH3ro** [BlackHyrax/Loading-Screen-Music#1]
Tried this mod and it seems to not play the songs i add in the folder, like it completly removes VRChats loading music but doesnt add the new one

**Comment by BlackHyrax** [comment]
did you rename the audiofile to Music.ogg since that is what the mod searches for!

**Comment by LilH3ro** [comment]
nvm fixed it was a space at the end that for some reason caused it to not work! Thanks for this mod btw!

**Comment by BlackHyrax** [comment]
I can look into that!

**Comment by BlackHyrax** [comment]
Multi file support got added

**Comment by LilH3ro** [comment]
How do you make it read multiple songs? because mine does not
